# Author: fasion
# Created time: 2019-07-20 14:56:34
# Last Modified by: fasion
# Last Modified time: 2019-07-22 09:27:55

build:
	javac HelloWorld.java

run:
	java HelloWorld

clean:
	rm -rf *.class
