# FileName:   Makefile
# Author:     Fasion Chan
# @contact:   fasionchan@gmail.com
# @version:   $Id$
#
# Description:
#
# Changelog:
#

.DEFAULT_GOAL := run

build: rebuild.c
	gcc -o rebuild rebuild.c

run: build
	./rebuild
