# FileName:   Makefile
# Author:     Fasion Chan
# @contact:   fasionchan@gmail.com
# @version:   $Id$
#
# Description:
#
# Changelog:
#

build:
	javac CommandLineArgs.java

run:
	java CommandLineArgs

clean:
	rm -rf *.class
