# Author: fasion
# Created time: 2019-07-20 14:56:34
# Last Modified by: fasion
# Last Modified time: 2019-07-22 11:34:32

build:
	javac NaiveArrayList.java

run:
	java NaiveArrayList

clean:
	rm -rf *.class
