# FileName:   Makefile
# Author:     Fasion Chan
# @contact:   fasionchan@gmail.com
# @version:   $Id$
#
# Description:
#
# Changelog:
#

demo: bubble-sort.c demo.c
	gcc -o $@ $^

run: demo
	./demo

clean:
	rm -rf demo
