# Author: fasion
# Created time: 2019-07-20 14:56:34
# Last Modified by: fasion
# Last Modified time: 2019-07-22 12:16:23

build:
	javac DynamicArrayList.java

run:
	java DynamicArrayList

clean:
	rm -rf *.class
