# Author: fasion
# Created time: 2019-07-20 14:56:34
# Last Modified by: fasion
# Last Modified time: 2019-07-22 11:34:25

build:
	javac GenericArrayList.java

run:
	java GenericArrayList

clean:
	rm -rf *.class
