# Author: fasion
# Created time: 2019-07-30 09:48:52
# Last Modified by: fasion
# Last Modified time: 2019-07-30 09:49:59

demo: single-linked-list.c demo.c
	gcc -o $@ $^

run: demo
	./demo

clean:
	rm -rf demo
